/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** OK */
        200: unknown
      }
    }
  }
  '/snips': {
    get: {
      parameters: {
        query: {
          id?: parameters['rowFilter.snips.id']
          code?: parameters['rowFilter.snips.code']
          password?: parameters['rowFilter.snips.password']
          user_id?: parameters['rowFilter.snips.user_id']
          created_at?: parameters['rowFilter.snips.created_at']
          expires_in?: parameters['rowFilter.snips.expires_in']
          language?: parameters['rowFilter.snips.language']
          /** Filtering Columns */
          select?: parameters['select']
          /** Ordering */
          order?: parameters['order']
          /** Limiting and Pagination */
          offset?: parameters['offset']
          /** Limiting and Pagination */
          limit?: parameters['limit']
        }
        header: {
          /** Limiting and Pagination */
          Range?: parameters['range']
          /** Limiting and Pagination */
          'Range-Unit'?: parameters['rangeUnit']
          /** Preference */
          Prefer?: parameters['preferCount']
        }
      }
      responses: {
        /** OK */
        200: {
          schema: definitions['snips'][]
        }
        /** Partial Content */
        206: unknown
      }
    }
    post: {
      parameters: {
        body: {
          /** snips */
          snips?: definitions['snips']
        }
        query: {
          /** Filtering Columns */
          select?: parameters['select']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** Created */
        201: unknown
      }
    }
    delete: {
      parameters: {
        query: {
          id?: parameters['rowFilter.snips.id']
          code?: parameters['rowFilter.snips.code']
          password?: parameters['rowFilter.snips.password']
          user_id?: parameters['rowFilter.snips.user_id']
          created_at?: parameters['rowFilter.snips.created_at']
          expires_in?: parameters['rowFilter.snips.expires_in']
          language?: parameters['rowFilter.snips.language']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
    patch: {
      parameters: {
        query: {
          id?: parameters['rowFilter.snips.id']
          code?: parameters['rowFilter.snips.code']
          password?: parameters['rowFilter.snips.password']
          user_id?: parameters['rowFilter.snips.user_id']
          created_at?: parameters['rowFilter.snips.created_at']
          expires_in?: parameters['rowFilter.snips.expires_in']
          language?: parameters['rowFilter.snips.language']
        }
        body: {
          /** snips */
          snips?: definitions['snips']
        }
        header: {
          /** Preference */
          Prefer?: parameters['preferReturn']
        }
      }
      responses: {
        /** No Content */
        204: never
      }
    }
  }
}

export interface definitions {
  snips: {
    /**
     * Format: character varying
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string
    /** Format: text */
    code: string
    /** Format: text */
    password?: string
    /** Format: uuid */
    user_id?: string
    /**
     * Format: time without time zone
     * @default now()
     */
    created_at: string
    /**
     * Format: public.expires
     * @enum {string}
     */
    expires_in?:
      | 'never'
      | '1h'
      | '2h'
      | '10h'
      | '1d'
      | '2d'
      | '1w'
      | '1m'
      | '1y'
      | null
    /** Format: text */
    language?: string | null
  }
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: 'params=single-object'
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: 'return=representation' | 'return=minimal' | 'return=none'
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: 'count=none'
  /** @description Filtering Columns */
  select: string
  /** @description On Conflict */
  on_conflict: string
  /** @description Ordering */
  order: string
  /** @description Limiting and Pagination */
  range: string
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string
  /** @description Limiting and Pagination */
  offset: string
  /** @description Limiting and Pagination */
  limit: string
  /** @description snips */
  'body.snips': definitions['snips']
  /** Format: character varying */
  'rowFilter.snips.id': string
  /** Format: text */
  'rowFilter.snips.code': string
  /** Format: text */
  'rowFilter.snips.password': string
  /** Format: uuid */
  'rowFilter.snips.user_id': string
  /** Format: time without time zone */
  'rowFilter.snips.created_at': string
  /** Format: public.expires */
  'rowFilter.snips.expires_in': string
  /** Format: text */
  'rowFilter.snips.language': string
}

export interface operations {}

export interface external {}
