[package]
name = "snip_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.6"
dotenv = "0.15.0"
mongodb = "3"
nanoid = "0.4.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version="0.4.38", features =["serde"] }
